name: tefterly CI

on:
  push:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  RUNTIME: win-x64
  SOLUTION_NAME: Tefterly.sln

jobs:
  build:
    runs-on: windows-latest  # WPF application must be build on Windows runners
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.3

    # Restore Nuget packages
    - name: Nuget Restore
      run: dotnet restore ${{env.SOLUTION_NAME}}
      env:
        Configuration: ${{ matrix.configuration }}
        Runtime: ${{ matrix.runtime }}   
        
    # Build the WPF application
    - name: Build the WPF application
      run: msbuild ${{env.SOLUTION_NAME}} /t:Restore /p:Configuration=${{env.BUILD_TYPE}} /p:RuntimeIdentifier=${{env.RUNTIME}}

    # Execute all unit tests in the solution
#    - name: Execute unit tests
#      run: dotnet test
